/* ============================================
   OBSIDIAN CUP — Language Translations
   EN + BN (Bengali)
   ============================================ */

const TRANSLATIONS = {
  en: {
    navHome: "Home", navTournaments: "Tournaments", navAbout: "About",
    navFaq: "FAQ", navRegister: "Register",
    heroEst: "Est. 2026", heroLocation: "Dhaka · Bangladesh",
    heroTitle: "Obsidian Cup",
    heroTagline: "Carved by Legacy · Crowned in Obsidian",
    announcedLabel: "Next Chapter",
    announcedTitle: "Football enters Obsidian",
    announcedSub: "June 2026 · A new field, the same Obsidian standard",
    announcedCategories: "Volleyball carved the first chapter. Football is the next arena.",
    viewResults: "Follow the launch →",
    pathsLabel: "Choose your path", pathsTitle: "The courts don't forget",
    path1Number: "01", path1Title: "The Seasons",
    path1Desc: "Three seasons. Every battle, every champion, every moment carved in obsidian. See the full legacy.",
    path1Link: "Explore the seasons →",
    path2Number: "02", path2Title: "Our Story",
    path2Desc: "How a group of friends who loved volleyball built something that belongs to everyone.",
    path2Link: "Read our story →",
    championsLabel: "Hall of legacy", championsTitle: "Past Champions",
    impact1Number: "3", impact1Label: "Seasons Completed",
    impact2Number: "26", impact2Label: "Teams Competed",
    impact3Number: "280+", impact3Label: "Players on Court",
    impact4Number: "80+", impact4Label: "Spectators",
    partnersLabel: "Those who believed early", partnersTitle: "Our Partners",
    partnersLabel2: "Those who believed early", partnersTitle2: "Our Partners",
    partnerCat1: "Hydration Partner", partnerCat2: "Apparel Partner",
    partnerNote: "Sponsor, OVASC Season 1",
    partnerCat3: "Official Sponsor", partnerNote3: "Sponsor, OVSC Season 2",
    socialLabel: "Stay in the loop", socialTitle: "Follow the Journey",
    socialDesc: "Match updates, fixture announcements, behind the scenes, and more — all on Instagram.",
    openInstagram: "Open Instagram", openFacebook: "Open Facebook",
    footerTagline: "Carved by Legacy, Crowned in Obsidian",
    aboutLabel: "The story", aboutTitle: "Our Story",
    aboutP1: "Obsidian Cup is a try. A genuine, wholehearted try at giving sports in Bangladesh the experience it actually deserves. Better venues, real production, and a standard of care that players can feel from the moment they step onto the field or court.",
    aboutP2: "Behind it is Uriana, with Tafhim holding things down on the field, and a founding circle, Masheer, Nabid, and Rifa, who are always there when it counts. No corporate backing, no big team. Just people who love the game and turn up every time.",
    aboutP3: "We want this magic to spread. The feeling of a well-run tournament, of a crowd that's alive, of walking off that court knowing the experience was worth everything. That feeling belongs to everyone. And we're here to make sure more people get to feel it. We started with two categories across two seasons — now we bring three together on one stage. This is just the beginning.",
    aboutQuote: "\"This isn't just a tournament. This is our air. We breathe it, we build it, we give it to everyone who steps on that court. Because through sport, we find ourselves. We find each other. And we find something worth fighting for.\"",
    aboutSub: "On this court we build lifelong friendships, real memories, and something that matters far beyond the final score.",
    visionLabel: "Where this is going", visionTitle: "The Vision",
    visionQuote: "\"We started with one cause. We plan to carry many more.\"",
    visionSub: "Volleyball was the beginning. But underground sport in Bangladesh deserves a real home across the board, not just one court. We want to be that home, for every sport, every player, every person who showed up and felt like they didn't belong anywhere else.",
    platformLabel: "The next chapter", platformTitle: "A Stage for Every Flame",
    platformP1: "We are working toward building a proper platform for our athletes. A space where those who burn with passion get the chance to show it. Where dedication is seen, where effort is recognised, where fire meets the audience it deserves.",
    platformP2: "In Bangladesh, most athletes never get that moment. They train, they compete, they give everything — and still go unrecognised. The system wasn't built for them. We want to change that, slowly, intentionally, and with real care. Starting with the courts we already know, and building outward from there.",
    platformClosing: "\"Every athlete deserves a stage. We're building it.\"",
    contactLabel: "Get in touch", contactTitle: "Contact", contactEmailLabel: "Email",
    tourLabel: "Every battle carved in history", tourTitle: "The Seasons",
    regLabel: "Team Registration — Now Open",
    regCategoryLabel: "Choose your category",
    regPayLabel: "After registering", regPayTitle: "Confirm Your Slot",
    faqLabel: "Got questions", faqTitle: "FAQ",
    faqSub: "Everything you need to know about Obsidian Cup.",
    faqGroup1: "About Obsidian Cup",
    faqGroup2: "Registration and Payment",
    faqGroup3: "Events and Match Day",
    faqGroup4: "Get in Touch",
    faq1q1: "What is Obsidian Cup?",
    faq1a1: "Obsidian Cup is an underground sports platform based in Dhaka, Bangladesh. We began with volleyball through OVC and OVASC, and football is next. Every format is designed to give players a proper, well-run competitive experience with stronger venues, production, atmosphere, and care.",
    faq1q2: "Who runs Obsidian Cup?",
    faq1a2: "Founded and run by Uriana, with Tafhim on the field and a core founding circle of Masheer, Nabid, and Rifa. No corporate backing, no large team — just people who love the game.",
    faq1q3: "How many seasons have you run?",
    faq1a3: "Three seasons across two volleyball tournament formats so far. OVC Season 1, OVASC Season 1, and the Obsidian Volleyball Super Cup in April 2026. Football joins the next chapter in June 2026.",
    faq1q4: "What sports do you cover?",
    faq1a4: "Volleyball is where we started. Our vision extends beyond it — more sports, more athletes, more stages are part of the plan.",
    faq2q1: "Does filling the registration form confirm my team's spot?",
    faq2q1a: "No. Your slot is never confirmed until payment is received and we issue an invoice. After submitting the form, send the fee via bKash, then email your transaction ID and screenshot to obsidiancup.official@gmail.com. Only then is your slot confirmed.",
    faq2q2: "What happens if I pay but don't send the transaction details?",
    faq2a2: "Your slot will not be confirmed. We cannot match a payment to a team without the transaction ID and screenshot. Always email us immediately after paying.",
    faq2q3: "What is the refund policy?",
    faq2a3: "Send a written cancellation via email at least 24 hours before the event for a 50% refund. No refund after this window.",
    faq2q4: "Can we change a player after registering?",
    faq2a4: "Before the registration deadline, yes — contact us via Instagram, Facebook, or email. After the deadline, changes are at our discretion.",
    faq3q1: "Is there an entry fee for spectators?",
    faq3a1: "No. All Obsidian Cup events are free for spectators.",
    faq3q2: "Will photos and videos be taken at events?",
    faq3a2: "Yes. By participating, players consent to their images being used for documentation and promotion across our social media channels.",
    faq3q3: "What happens if an event is cancelled or the venue changes?",
    faq3a3: "We will notify all registered teams immediately. If the event cannot be rescheduled, a full refund will be issued.",
    faq4q1: "How do I contact Obsidian Cup?",
    faq4a1: "Email: obsidiancup.official@gmail.com",
  },

  bn: {
    navHome: "হোম", navTournaments: "টুর্নামেন্ট", navAbout: "আমাদের সম্পর্কে",
    navFaq: "প্রশ্নোত্তর", navRegister: "নিবন্ধন",
    heroEst: "প্রতিষ্ঠিত ২০২৬", heroLocation: "ঢাকা · বাংলাদেশ",
    heroTitle: "Obsidian Cup",
    heroTagline: "Carved by Legacy · Crowned in Obsidian",
    announcedLabel: "পরবর্তী অধ্যায়",
    announcedTitle: "Football enters Obsidian",
    announcedSub: "জুন ২০২৬ · নতুন মাঠ, একই Obsidian মান",
    announcedCategories: "ভলিবল প্রথম অধ্যায় লিখেছে। ফুটবল পরবর্তী মঞ্চ।",
    viewResults: "লঞ্চ অনুসরণ করুন →",
    pathsLabel: "আপনার পথ বেছে নিন",
    pathsTitle: "কোর্ট কখনো ভুলে না",
    path1Number: "০১", path1Title: "সিজনসমূহ",
    path1Desc: "তিনটি সিজন। প্রতিটি লড়াই, প্রতিটি চ্যাম্পিয়ন, অবসিডিয়ানে খোদাই প্রতিটি মুহূর্ত।",
    path1Link: "সিজন অন্বেষণ করুন →",
    path2Number: "০২", path2Title: "আমাদের গল্প",
    path2Desc: "কীভাবে ভলিবলকে ভালোবাসা কিছু বন্ধু এমন কিছু গড়ে তুলল যা সবার।",
    path2Link: "গল্প পড়ুন →",
    championsLabel: "উত্তরাধিকারের হল", championsTitle: "সাবেক চ্যাম্পিয়ন",
    impact1Number: "৩", impact1Label: "সম্পন্ন সিজন",
    impact2Number: "২৬", impact2Label: "প্রতিযোগী দল",
    impact3Number: "২৮০+", impact3Label: "কোর্টে খেলোয়াড়",
    impact4Number: "৮০+", impact4Label: "দর্শক",
    partnersLabel: "যারা আগে বিশ্বাস রেখেছিলেন", partnersTitle: "আমাদের অংশীদার",
    partnersLabel2: "যারা আগে বিশ্বাস রেখেছিলেন", partnersTitle2: "আমাদের অংশীদার",
    partnerCat1: "হাইড্রেশন পার্টনার", partnerCat2: "অ্যাপারেল পার্টনার",
    partnerNote: "স্পনসর, OVASC সিজন ১",
    partnerCat3: "অফিশিয়াল স্পনসর", partnerNote3: "স্পনসর, OVSC সিজন ২",
    socialLabel: "সংযুক্ত থাকুন", socialTitle: "যাত্রা অনুসরণ করুন",
    socialDesc: "ম্যাচ আপডেট, ফিকচার ঘোষণা, পর্দার পেছনের দৃশ্য এবং আরও অনেক কিছু — ইনস্টাগ্রামে।",
    openInstagram: "ইনস্টাগ্রাম খুলুন", openFacebook: "ফেসবুক খুলুন",
    footerTagline: "Carved by Legacy, Crowned in Obsidian",
    aboutLabel: "গল্পটি", aboutTitle: "আমাদের গল্প",
    aboutP1: "Obsidian Cup একটি চেষ্টা। বাংলাদেশের খেলাধুলাকে সত্যিকারের মানসম্মত অভিজ্ঞতা দেওয়ার একটি আন্তরিক চেষ্টা। ভালো ভেন্যু, সত্যিকারের প্রোডাকশন, এবং এমন একটি যত্নের মান যা খেলোয়াড়রা মাঠ বা কোর্টে পা দেওয়ার মুহূর্ত থেকেই অনুভব করতে পারেন।",
    aboutP2: "এর পেছনে আছেন Uriana, মাঠে সবকিছু সামলান Tafhim, আর প্রতিষ্ঠাতা বৃত্তে আছেন Masheer, Nabid এবং Rifa — যারা প্রতিবার দরকারে হাজির থাকেন।",
    aboutP3: "আমরা চাই এই জাদু ছড়িয়ে পড়ুক। একটি সুসংগঠিত টুর্নামেন্টের অনুভূতি, একটি জীবন্ত দর্শক সারির অনুভূতি — এই অনুভূতি সবার জন্য।",
    aboutQuote: "\"এটা শুধু একটা টুর্নামেন্ট নয়। এটা আমাদের নিঃশ্বাস। আমরা এটা শ্বাস নিই, এটা গড়ি, আর এটা দিই প্রত্যেককে যে এই কোর্টে পা রাখে।\"",
    aboutSub: "এই কোর্টে আমরা গড়ি আজীবনের বন্ধুত্ব, সত্যিকারের স্মৃতি।",
    visionLabel: "আমরা যেদিকে যাচ্ছি", visionTitle: "আমাদের লক্ষ্য",
    visionQuote: "\"আমরা একটি লক্ষ্য নিয়ে শুরু করেছিলাম। আরও অনেক লক্ষ্য বহন করার পরিকল্পনা আছে।\"",
    visionSub: "ভলিবল ছিল শুরুটা। কিন্তু বাংলাদেশের আন্ডারগ্রাউন্ড স্পোর্টস একটি সত্যিকারের আবাস চায়। আমরা সেই আবাস হতে চাই।",
    platformLabel: "পরবর্তী অধ্যায়", platformTitle: "প্রতিটি শিখার জন্য একটি মঞ্চ",
    platformP1: "আমরা আমাদের অ্যাথলেটদের জন্য একটি সত্যিকারের প্ল্যাটফর্ম গড়ে তোলার দিকে কাজ করছি। এমন একটি জায়গা যেখানে যারা আবেগে জ্বলেন তারা সেটা দেখাতে পারেন।",
    platformP2: "বাংলাদেশে বেশিরভাগ অ্যাথলেট সেই মুহূর্তটা কখনো পান না। তারা অনুশীলন করেন, প্রতিযোগিতায় অংশ নেন, সব দেন — তবুও অচেনা থেকে যান। আমরা সেটা বদলাতে চাই।",
    platformClosing: "\"প্রতিটি অ্যাথলেট একটি মঞ্চ পাওয়ার যোগ্য। আমরা সেটা তৈরি করছি।\"",
    contactLabel: "যোগাযোগ করুন", contactTitle: "যোগাযোগ", contactEmailLabel: "ইমেইল",
    tourLabel: "ইতিহাসে খোদাই প্রতিটি লড়াই", tourTitle: "সিজনসমূহ",
    regLabel: "দল নিবন্ধন — এখন খোলা",
    regCategoryLabel: "আপনার বিভাগ বেছে নিন",
    regPayLabel: "নিবন্ধনের পরে", regPayTitle: "আপনার স্লট নিশ্চিত করুন",
    faqLabel: "প্রশ্ন আছে?", faqTitle: "প্রশ্নোত্তর",
    faqSub: "Obsidian Cup সম্পর্কে যা জানা দরকার।",
    faqGroup1: "Obsidian Cup সম্পর্কে",
    faqGroup2: "নিবন্ধন ও পেমেন্ট",
    faqGroup3: "ইভেন্ট ও ম্যাচ ডে",
    faqGroup4: "যোগাযোগ করুন",
    faq1q1: "Obsidian Cup কী?",
    faq1a1: "Obsidian Cup ঢাকা, বাংলাদেশ ভিত্তিক একটি ভলিবল টুর্নামেন্ট ব্র্যান্ড। আমরা OVC এবং OVASC পরিচালনা করি — দুটি টুর্নামেন্ট ফরম্যাট যা প্রতিটি স্তরের খেলোয়াড়দের একটি সঠিক, সুসংগঠিত প্রতিযোগিতামূলক অভিজ্ঞতা দিতে ডিজাইন করা হয়েছে।",
    faq1q2: "Obsidian Cup কারা পরিচালনা করে?",
    faq1a2: "Uriana প্রতিষ্ঠিত ও পরিচালিত, মাঠে Tafhim এবং প্রতিষ্ঠাতা বৃত্তে Masheer, Nabid এবং Rifa।",
    faq1q3: "কয়টি সিজন হয়েছে?",
    faq1a3: "দুটি টুর্নামেন্ট ফরম্যাটে তিনটি সিজন। এখন পর্যন্ত ২৬টিরও বেশি দল এবং ২৮০ জনেরও বেশি খেলোয়াড় অংশগ্রহণ করেছে।",
    faq1q4: "আপনারা কোন খেলা কভার করেন?",
    faq1a4: "ভলিবল দিয়ে শুরু। কিন্তু আমাদের দৃষ্টিভঙ্গি এর বাইরেও — আরও খেলা, আরও অ্যাথলেট, আরও মঞ্চ পরিকল্পনার অংশ।",
    faq2q1: "নিবন্ধন ফর্ম পূরণ করলে কি আমার দলের স্লট নিশ্চিত হয়?",
    faq2q1a: "না। পেমেন্ট না পাওয়া পর্যন্ত স্লট কখনো নিশ্চিত হয় না। ফর্ম জমা দেওয়ার পরে bKash-এ ফি পাঠান, তারপর ট্রানজেকশন আইডি ও স্ক্রিনশট obsidiancup.official@gmail.com-এ ইমেইল করুন। তখনই স্লট নিশ্চিত হবে।",
    faq2q2: "পেমেন্ট করলে কিন্তু ট্রানজেকশন বিবরণ না পাঠালে কী হবে?",
    faq2a2: "আপনার স্লট নিশ্চিত হবে না। ট্রানজেকশন আইডি ও স্ক্রিনশট ছাড়া আমরা পেমেন্ট দলের সাথে মেলাতে পারব না।",
    faq2q3: "রিফান্ড পলিসি কী?",
    faq2a3: "ইভেন্টের কমপক্ষে ২৪ ঘণ্টা আগে ইমেইলে লিখিত বাতিলের অনুরোধ পাঠালে ৫০% রিফান্ড দেওয়া হবে। এরপরে কোনো রিফান্ড নেই।",
    faq2q4: "নিবন্ধনের পর কি খেলোয়াড় পরিবর্তন করা যাবে?",
    faq2a4: "নিবন্ধনের শেষ তারিখের আগে হ্যাঁ। শেষ তারিখের পরে পরিবর্তন আমাদের বিবেচনার ভিত্তিতে।",
    faq3q1: "দর্শকদের জন্য কি প্রবেশ ফি আছে?",
    faq3a1: "না। সকল Obsidian Cup ইভেন্টে দর্শকরা বিনামূল্যে প্রবেশ করতে পারবেন।",
    faq3q2: "ইভেন্টে কি ছবি ও ভিডিও তোলা হবে?",
    faq3a2: "হ্যাঁ। অংশগ্রহণ করে খেলোয়াড়রা তাদের ছবি ও ভিডিও প্রচারের জন্য ব্যবহারের সম্মতি দিচ্ছেন।",
    faq3q3: "ইভেন্ট বাতিল বা ভেন্যু পরিবর্তন হলে কী হবে?",
    faq3a3: "আমরা তাৎক্ষণিকভাবে সকল নিবন্ধিত দলকে জানাব। পুনরায় নির্ধারণ না করা গেলে সম্পূর্ণ অর্থ ফেরত দেওয়া হবে।",
    faq4q1: "Obsidian Cup-এর সাথে কীভাবে যোগাযোগ করব?",
    faq4a1: "ইমেইল: obsidiancup.official@gmail.com",
  }
};

function setLanguage(lang) {
  const selected = TRANSLATIONS[lang] ? lang : 'en';
  document.querySelectorAll('[data-key]').forEach(el => {
    const key = el.getAttribute('data-key');
    if (TRANSLATIONS[selected] && TRANSLATIONS[selected][key]) {
      el.textContent = TRANSLATIONS[selected][key];
    }
  });
  localStorage.setItem('oc_lang', selected);
  document.querySelectorAll('.lang-btn').forEach(btn => {
    btn.classList.toggle('lang-btn-active', btn.getAttribute('data-lang') === selected);
  });
  document.documentElement.lang = selected === 'bn' ? 'bn' : 'en';
}

function initLanguage() {
  const saved = localStorage.getItem('oc_lang');
  const selected = saved === 'bn' ? 'bn' : 'en';
  document.documentElement.lang = selected === 'bn' ? 'bn' : 'en';
  setLanguage(selected);
}

(function() {
  const saved = localStorage.getItem('oc_lang');
  document.documentElement.lang = saved === 'bn' ? 'bn' : 'en';
})();
